<?php
   $data1=$_POST['collg'];
   $data2=$_POST['date'];
   $data3=$_POST['paperss'];
   $data4=$_POST['branchss'];
   $data5=$_POST['semss'];
   $data6=$_POST['code'];
   $data7=$_POST['subss'];
   $data8=$_POST['qno'];
   $data9=$_POST['qp'];
   $data10=$_POST['time'];
   $data11=$_POST['marks'];
   $data12=$_POST['questa'];
   $data13=$_POST['questb'];
   require('fpdf.php');
   $pdf= new FPDF();
   $pdf->AddPage();
   $pdf->SetFont('Times', 'B', 15); 
   $pdf->Cell(176, 15, $data1, 0, 0, 'C'); 
   $pdf->Ln(); 
   $pdf->SetFont('Times', 'B', 17); 
   $pdf->Cell(176, 10, $data4, 0, 0, 'C');
   $pdf->Ln(); 
   $pdf->SetFont('Times', 'B', 17); 
   $pdf->Cell(176, 10, $data3, 0, 0, 'C');
   $pdf->Ln(); 
   $pdf->SetFont('Times', 'B', 14); 
   $pdf->Cell(25, 10, "Semester:", 0, 0, 'L');
   $pdf->SetFont('Times', 'B', 14); 
   $pdf->Cell(10, 10, $data5, 0, 0, 'L');
   $pdf->SetFont('Times', 'B', 14); 
   $pdf->Cell(150, 10, "Total question:", 0, 0, 'R');
   $pdf->SetFont('Times', 'B', 14); 
   $pdf->Cell(7, 10, $data8, 0, 0, 'R');
   $pdf->Ln(); 
   $pdf->SetFont('Times', 'B', 14); 
   $pdf->Cell(20, 10, "Subject:", 0, 0, 'L');
   $pdf->SetFont('Times', 'B', 14); 
   $pdf->Cell(5, 10, $data7, 0, 0, 'L');
   $pdf->SetFont('Times', 'B', 14);
   $pdf->Cell(156, 10, "Total marks:", 0, 0, 'R');
   $pdf->SetFont('Times', 'B', 14); 
   $pdf->Cell(7, 10, $data11, 0, 0, 'R');
   $pdf->Ln(); 
   $pdf->SetFont('Times', 'B', 14); 
   $pdf->Cell(32, 10, "Subject Code:", 0, 0, 'L');
   $pdf->SetFont('Times', 'B', 14); 
   $pdf->Cell(10, 10, $data6, 0, 0, 'L');
   $pdf->SetFont('Times', 'B', 14); 
   $pdf->Cell(145, 10, "Time Duration:", 0, 0, 'R');
   $pdf->Cell(13, 10, $data10, 0, 1, 'R');
   $pdf->SetFont('Times', 'B', 14); 
   $pdf->Cell(176, 25, "General Instructions", 0, 1, 'C'); 
   $pdf->SetFont('Times', 'I',13); 
   $pdf->MultiCell(0, 5, $data9); 
   $pdf->Line(5, 45, 205, 45);
   $pdf->ln(5);
   $pdf->SetFont('Times', 'U', 14); 
   $pdf->Cell(176, 25, 'SECTION A', 0, 1, 'C');
   $pdf->SetFont('Times', 'B', 14);
   $pdf->Cell(176, 2, '1x5=5', 0, 1, 'R');  
   $pdf->SetFont('Arial', 'B', 12); 
   $pdf->MultiCell(0, 7, $data12); 
   $pdf->ln(2);
   $pdf->SetFont('Times', 'U', 14); 
   $pdf->Cell(176, 25, 'SECTION B', 0, 1, 'C');
   $pdf->SetFont('Times', 'B', 14);
   $pdf->Cell(176, 2, '3x5=15', 0, 1, 'R'); 
   $pdf->SetFont('Arial', 'B', 12); 
   $pdf->MultiCell(0, 7, $data13);  
   $pdf->output();
?>
</body>
</html>